#!/bin/sh /etc/rc.common
START=99
STOP=99

PATH=$PATH:/usr/bin:/bin
start() {
		echo "Starting aquacc daemon" >> /var/log/messages
		/usr/local/bin/aquacc
		/root/temp_client.py >> /var/log/messages &
}

stop() {
		killall /usr/local/bin/aquacc
		killall temp_client.py
}
